#!/usr/bin/env bash

dk use: dotenv

on boot mantle-bootstrap
on setup mantle-setup

mantle-bootstrap() {
	# Route in-container commands via docker-compose
	for REPLY in imposer composer wp dba; do have "$REPLY" || catbin "$REPLY" <<-EOF
	#!/usr/bin/env bash
	exec doco $REPLY "\$@"
	EOF
	done

	require-any doco github bashup/doco master bin/doco
	require-any jq
	require-any docker-compose
	mkdir -p deploy
}

mantle-setup() {
	if [[ ! -f .env ]]; then
		cp share/example.env .env
		echo ".env file created -- you may wish to edit it"
		echo
	fi

	REPLY=(*.doco.md)
	if [[ $REPLY == "*.doco.md" ]]; then
		realpath.basename "$PWD"
		cp share/sample-config.md "$REPLY".doco.md
		echo -n "$REPLY.doco.md configuration file created: "
		echo -n "Edit it to define your sites (and rename if you wish, as long "
		echo "as it retains the .doco.md suffix)."
	fi
} >&2;
